'''
	Generates a random list

	The list is generated by assuming the unsorted list Generate
	completely unsorted list
'''
import random as R

def generateList(size, presortedness):
	'''
	The function return a list with random values.

	Args:
		size (int): The size of the list to be generated.
		presortedness (float(0 - 1)): How much the list should be sorted
			1 - the list is 100 % sorted.
			0 - the list is 0 % sorted.
	Return:
		list with the length of size
	'''
	sequence = []
	if size >= 0:

		sortList, unsortedList = [], []
		sortList = R.sample(xrange(100), int(presortedness*size))
		sortList.sort()
		unsortedList = R.sample(xrange(100), size - len(sortList))
		if R.randint(0,1):
			sequence = sortList + unsortedList
		else:
			sequence = unsortedList + sortList

		return sequence
	else:
		return sequence

if __name__ == '__main__':
	for i in range(0, 100, 25):
		print generateList(10, i / 100)
